### ISSUE TITLE
Missing `tomlkit`

### ISSUE THREAD

**Issue by cschwan** [NNPDF/runcards#130]
At least on `dom` on the `DIS-more` branch I get:

```
Error processing line 1 of /home/cschwan/.local/lib/python3.10/site-packages/zzz_poetry_dynamic_versioning.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/cschwan/.local/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 13, in <module>
      import tomlkit
  ModuleNotFoundError: No module named 'tomlkit'
```

**Comment by AleCandido** [comment]
Can you add details on how to reproduce, please? (i.e. which command did you launch)

**Comment by AleCandido** [comment]
Not reproduced  locally, I'm going to try on `dom`

**Comment by cschwan** [comment]
That's strange:

```
cschwan@dom runcards $ which pip
/usr/bin/pip
cschwan@dom runcards $ pip show tomlkit
Error processing line 1 of /home/cschwan/.local/lib/python3.10/site-packages/zzz_poetry_dynamic_versioning.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/cschwan/.local/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 13, in <module>
      import tomlkit
  ModuleNotFoundError: No module named 'tomlkit'

Remainder of file ignored
Name: tomlkit
Version: 0.9.1
Summary: Style preserving TOML library
Home-page: https://github.com/sdispater/tomlkit
Author: Sébastien Eustace
Author-email: sebastien@eustace.io
License: UNKNOWN
Location: /usr/lib/python3.10/site-packages
Requires: 
Required-by: poetry-dynamic-versioning, poetry
```

**Comment by AleCandido** [comment]
I've just run:

```sh
./rr run nnpdf31_proc/HERA_CC_318GEV_EM_SIGMARED theories/theory_213.yaml
```

on `dom`, and it worked.

**Comment by felixhekhorn** [comment]
@cschwan this seems to me like your `poetry-dynamic-versioning` installation is somehow corrupted ... as far as I understood it has to be installed alongside `poetry` (meaning in the very same environment)

what do you get on
```
felix@FHe19b:~$ pip list | grep poetry
poetry                        1.1.12
poetry-core                   1.0.7
poetry-dynamic-versioning     0.13.0
```
and
```
felix@FHe19b:~$ which poetry
/home/felix/.local/bin/poetry
```

see also https://github.com/mtkennerly/poetry-dynamic-versioning#installation

and `tomlkit` is a direct dependency https://github.com/mtkennerly/poetry-dynamic-versioning/blob/eac2f68f6e01f6e336dfb6c23a4c90911c12f013/pyproject.toml#L28 so pip has messed up, maybe?

**Comment by cschwan** [comment]
There you go:

```
cschwan@dom runcards $ pip list | grep poetry
poetry                        1.1.13
poetry-core                   1.0.7
cschwan@dom runcards $ which poetry
/usr/bin/poetry
```

**Comment by cschwan** [comment]
I understand what you're saying, but in a sense that defeats the purpose of `./rr` - I don't care about poetry or any other Python package, I just want to generate processes.

**Comment by felixhekhorn** [comment]
Mmm but that's like saying "I just want to play that game" and then missing on the video driver, no?

**Comment by AleCandido** [comment]
Actually, I believe this will be solved by #127 and #128.

The workflow I have in mind is the following:
- if you're a developer, you're in charge to install `poetry` & co. by yourself
- otherwise, you can just use `pip install`, both with the remote version (`pip install <runcards-runner-final-name>`) and with the local one (`pip install .`)

Once you install with `pip`, then `rr` or its replacement will be available as command, and it will take the place of `./rr`.
Instructions for developers are delicate and we can even spell personally (we will write something, but I'd expect it might fail in general if very detailed), instructions for everyone else will be simple, even without `./rr`.

Eventually, when `poetry` will release `1.2.0`, we will get even editable mode with `pip` for free.

**Comment by cschwan** [comment]
> Mmm but that's like saying "I just want to play that game" and then missing on the video driver, no?

True :smile:, and I've worded my statement probably more strongly than I felt, because - at least subjectively - 'poetry' keeps breaking time and again for me.

I've just recently realized that what I had in mind concerning the design of our runner was the containerization of the runcards runner; this would solve all the version and installation problems reliably.

**Comment by AleCandido** [comment]
I keep thinking about `poetry`, that's also the feeling of @scarlehoff for example.

But analyzing all the issues one by one, what I currently believe is that `poetry` failures are just the signal of us doing something bad (mostly with versions). So, in most cases it's leading to early detection of inconsistencies.

This applies to all the restrictions on the python versions, or the dependency on various packages, but it does not apply to the issues related to poetry installation and environment management.
About this second category I believe the solution to be to use more scripts (like `ŧest` or `run` and so on), that we can write once and they are proved to work, plus the one written above: for actual usage (not development) rely on `pip` installation.

Moreover, there are the problems related to the installation of `poetry` itself: this is almost a non-problem, I created it myself with the installation script (I believe)...

**Comment by cschwan** [comment]
@AleCandido I agree with what you said; I've put 'poetry' in quotation marks in my comment above, because it's a little bit unfair to blame poetry for all problems, of course!

**Comment by scarlehoff** [comment]
To be completely honest, one of the reasons the `python` ecosystem is broken in dom is because we tried to be too clever using the same python environment for 4 different people... I'm actually amazed at how well it works most of the time.

we have < system>(shared) < FK>(shared) <.local>(each has their own)

in general < system> should always be consistent because is coming from the arch repositories with no `pip` installation and < FK> is used often enough that when it breaks someone will realise, so in dom the most likely solution most of the time is to remove all home-installed packages and then try again ...

**Comment by AleCandido** [comment]
> I agree, but keep in mind for that a necessary pre-requisite is settling a final name

I'd have said so as well, but at this point I believe we won't have a final name in less than one month and something, i.e. code meeting/collaboration meeting.
So, at this point I don't care any longer, I'll keep acting as if the name is final, and I'll pay the price of renaming stuffs afterwards.

> This applies to all the restrictions on the python versions, or the dependency on various packages, but it does not apply to the issues related to poetry installation and environment management.

Another relevant consideration is that `poetry` is not mandatory. Actually, it violates the UNIX philosophy, in the sense that a single tool is performing two tasks (even if the two are quite coupled):
- **packaging**: this we could get even with `setuptools`, but packaging is only needed for releases and easier distribution, so this not mandatory neither for development, nor for usage (you can always use the source, it's a valid python package even if you don't create a distribution package)
- **environment management**: even this aspect is opt-in, since you can always decide to maintain your own virtual environment with `virtualenv` or whatever you prefer, simply you will have to manage dependencies on your own

At the end of the day, `poetry` is adding something (arguably including overhead... quite for sure overhead...), but it's removing nothing, so if it doesn't work for you, you can always use whatever you prefer.
